games/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AllGamesView.as_view(), name='games_list'),
    path('<int:pk>',views.GameView.as_view(), name='game_detail'),
    path('new', views.game_new, name='game_new'),
    path('edit/<int:pk>', views.game_edit, name='game_edit'),
    path('review/<int:gid>/<int:uid>',views.create_review, name='create_review'),
    path('reviewlike/<int:gid>/<int:rid>/<int:uid>/', views.like_review, name='like_review'),
    path('reviewdislike/<int:gid>/<int:rid>/<int:uid>/', views.dislike_review, name='dislike_review'),
]

projectsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('games.urls')),
    path('studios/',include('studios.urls')),
    path('publishers/', include('publishers.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('users/',include('users.urls')),
    path('captcha/', include('captcha.urls')),
    path(r'^tracking', include('tracking.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

publishers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AllPublishersView.as_view(), name='publishers_list'),
    path('<int:pk>/', views.PublisherView.as_view(), name='publisher_detail'),
    path('new', views.publisher_new, name='publisher_new'),
    path('edit/<int:pk>', views.publisher_edit, name='publisher_edit'),
]

publishers/models.py
from django.db import models

from hitcount.models import HitCount
from hitcount.models import HitCountMixin

from django.contrib.contenttypes.fields import GenericRelation

class Publisher(models.Model, HitCountMixin):
    name = models.CharField(max_length=100,verbose_name='Издатель')
    desc = models.TextField(verbose_name='Описание')
    founder = models.CharField(max_length=200,verbose_name='Основатель')
    founded = models.DateField(verbose_name='Основано')
    headquarters = models.CharField(max_length=200,verbose_name='Адрес')
    main_site = models.URLField(max_length=200,verbose_name='Главная Страница')
    is_active = models.BooleanField(default=True,verbose_name='Активен')

    hit_count_generic = GenericRelation(
        HitCount, 
        object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')

    def current_hitcount(self):
        return self.hit_count.hits
    
    def current_hitcount_in_last(self, num):
        return self.hit_count.hits_in_last(days=num)

    def __str__(self) -> str:
        return self.name

publishers/forms.py
from django import forms
from .models import Publisher

class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = '__all__'
        exclude = ('is_active',)

publishers/views.py
from typing import Any, Dict
from django.shortcuts import render,redirect
from .models import Publisher
from games.models import Game
from .forms import PublisherForm
from django.views.generic import ListView,DetailView

from hitcount.views import HitCountDetailView

class AllPublishersView(ListView):
    model = Publisher
    template_name = 'publisher/publishers_list.html'
    # queryset = 
    paginate_by = 4
    context_object_name = 'publishers'
    
class PublisherView(HitCountDetailView):
    model = Publisher
    template_name = 'publisher/publisher_detail.html'
    context_object_name = 'publisher'
    count_hit = True
    
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        games_list = Game.objects.filter(publisher = context['publisher'].pk)
        context['games_list'] = games_list
        context.update({
            'recommended': Publisher.objects.filter(is_active = True).exclude(pk = context['publisher'].pk).order_by('-hit_count_generic__hits')[:3]
        })
        return context
# def publishers_list(request):
#     publishers = Publisher.objects.all()
#     for i in range(len(publishers)):
#         publishers[i].games_list = Game.objects.filter(publisher = publishers[i].pk).all()
#     return render(request, "publisher/publishers_list.html", {"publishers":publishers})

    
# def publisher_detail(request,pk):
#     publisher = get_object_or_404(Publisher, pk=pk)
#     games_list = Game.objects.filter(publisher = publisher.pk).all()
#     return render(request, 'publisher/publisher_detail.html',{'publisher':publisher, 'games_list':games_list})

def publisher_new(request):
    if request.method == "POST":    
        form = PublisherForm(request.POST, request.FILES)
        if form.is_valid():
            publisher = form.save(commit=False)
            publisher.save()
            return redirect('publisher_detail', pk=publisher.pk)
    else:
        form = PublisherForm()
    return render(request, 'publisher/publisher_new.html', {'form':form})

def publisher_edit(request, pk):
    publisher = Publisher.objects.get(pk=pk)
    if request.method == "POST":
        form = PublisherForm(request.POST, request.FILES, instance=publisher)
        if form.is_valid():
            publisher = form.save(commit=False)
            publisher.save()
            return redirect('publisher_detail', pk=publisher.pk)
    else:
        form = PublisherForm(instance=publisher)
    return render(request, 'publisher/publisher_new.html', {'form':form})

templates/publisher/publisher_detail.html
{% extends 'games/base.html' %}
{% load hitcount_tags %}
 
{% block content %}
<div class="game_card" style="border-bottom: 2px black solid; margin: 10px;">    
    <div class="game_card_top">
        <div class="game_title">
            <p class>{{publisher.name}}</p>
        </div>
        {% if perms.publishers.change_publisher %}
        <div class="game_edit">
            <a href="{% url 'publisher_edit' pk=publisher.pk %}">
                {% include 'icons/three-dots-vertical.svg' %}
            </a>
        </div>
        {% endif %}
    </div>
    <!-- <img src="/media/{{publisher.logo}}" alt=""> -->
    <p>{{publisher.headquarters}}</p>
    <p>{{publisher.main_site}}</p>
    <p>{{publisher.founder}}</p>
    <p>{{publisher.founded}}</p>
    <p>Views: {% get_hit_count for publisher %}</p>
    {% for game in games_list %}
        <p>{{game.title}}</p> 
    {% endfor %} 
</div>
<div class="recommended">
    {% for rec in recommended %}
        <a href="{% url 'publisher_detail' pk=rec.pk %}">{{rec.name}}</a>
    {% endfor %}
</div>
{% endblock %}

templates/publisher/publisher_new.html
{% extends 'games/base.html' %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

templates/publisher/publishers_list.html
{% extends "games/base.html" %}
{% block new %}
{% if perms.publishers.change_publisher %}
    <a href="{% url 'publisher_new' %}" style="float: left; font-size: 50px; margin-top: 50px; margin-left: 50px;">
        {% include '../icons/file-earmark-plus.svg' %}
    </a>
{% endif %}
{% endblock%}
{% block content %}
    {% for publisher in publishers %}
        <div class="game_card">  
            <a href="{% url 'publisher_detail' pk=publisher.pk%}"><p class="game_title">{{publisher.name}}</p></a>
            <p>{{publisher.founded}}</p>
            <p>{{publisher.desc}}</p>
        </div>
    {% endfor %}
{% endblock %}