games/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AllGamesView.as_view(), name='games_list'),
    path('<int:pk>',views.GameView.as_view(), name='game_detail'),
    path('new', views.game_new, name='game_new'),
    path('edit/<int:pk>', views.game_edit, name='game_edit'),
    path('review/<int:gid>/<int:uid>',views.create_review, name='create_review'),
    path('reviewlike/<int:gid>/<int:rid>/<int:uid>/', views.like_review, name='like_review'),
    path('reviewdislike/<int:gid>/<int:rid>/<int:uid>/', views.dislike_review, name='dislike_review'),
]

projectsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('games.urls')),
    path('studios/',include('studios.urls')),
    path('publishers/', include('publishers.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('users/',include('users.urls')),
    path('captcha/', include('captcha.urls')),
    path(r'^tracking', include('tracking.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

games/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from studios.models import Studio
from publishers.models import Publisher

from hitcount.models import HitCount
from hitcount.models import HitCountMixin

from django.contrib.contenttypes.fields import GenericRelation

class Game(models.Model, HitCountMixin):
    title = models.CharField(max_length=200, verbose_name='Название')
    poster = models.ImageField(upload_to='game_posters',null=True, verbose_name='Обложка')
    trailer_url = models.URLField(max_length=200,null=True, blank=True, verbose_name='Трейлер (Ссылка)')
    studio = models.ForeignKey(Studio,on_delete=models.PROTECT,null=True,blank=True, verbose_name='Студия Разработчик')
    genre = models.ForeignKey('Genre',on_delete=models.PROTECT,verbose_name="Жанр")
    style = models.CharField(max_length=200, verbose_name='Стиль')
    desc = models.TextField(verbose_name='Описание')
    release_date = models.DateField(verbose_name='Дата Релиза')
    publisher = models.ForeignKey(Publisher,on_delete=models.PROTECT,null=True,blank=True,verbose_name='Издатель')
    rating_metacritic = models.IntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(100), 
        ],
        verbose_name='Оценка Metacritic'
    )   
    rating_ign = models.FloatField(
        validators=[
            MinValueValidator(0.0),
            MaxValueValidator(10.0)
        ], 
        verbose_name='Оценка IGN'
    )
    engine = models.CharField(max_length=100, verbose_name='Игровой Движок')
    price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        validators=[
            MinValueValidator(0.0),
        ], 
        verbose_name='Цена $'
    )
    is_active = models.BooleanField(default=True, verbose_name='Активен')

    hit_count_generic = GenericRelation(
        HitCount, 
        object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')
    
    def current_hitcount(self):
        return self.hit_count.hits
    
    def current_hitcount_in_last(self, num):
        return self.hit_count.hits_in_last(days=num)

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse('game_detail',args=[str(self.id)])
    
    class Meta:
        verbose_name = 'Игра'
        verbose_name_plural = 'Игры'
        ordering = ['-release_date','title']

from django.contrib.auth.models import User
from django.utils import timezone

class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    rating_date = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    rating_choise = (
        (0,0),
        (1,1),
        (2,2),
        (3,3),
        (4,4),
        (5,5)
    )
    rating = models.IntegerField(choices=rating_choise, default=6, verbose_name='Рейтинг')
    comment = models.TextField(verbose_name='Ревью')
    game = models.ForeignKey(Game, on_delete=models.CASCADE, verbose_name='Игра')

    def __str__(self) -> str:
        return f'{self.game.title} by {self.author}'

class ReviewLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    value_choise=(
        (0,0),
        (1,1),
    )
    value = models.IntegerField(choices=value_choise)

    def __str__(self) -> str:
        return f'Review: {self.review} | User: {self.user} {self.value}'

class Genre(models.Model):
    genre = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.genre

games/forms.py
from django import forms
from .models import Game, Review

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = '__all__'
        exclude = ('is_active',)

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('rating','comment')

games/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from .models import Game, Review, ReviewLike
from .forms import GameForm, ReviewForm
# from django.views.generic import ListView,DetailView
from django_filters.views import FilterView
from .filter import GameFilter

from hitcount.views import HitCountDetailView

class AllGamesView(FilterView):
    model = Game
    paginate_by = 2
    template_name = 'games/games_list.html'
    queryset = Game.objects.filter(is_active = True).order_by('-release_date')
    filterset_class = GameFilter
    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset
        # context['form'] = GameSearch(self.request.get)
        return context
        # if query is not None:
            
# def create_review(gid,uid):

from django.db.models import Sum

class GameView(HitCountDetailView):
    model = Game
    count_hit = True
   
    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        if context['game'].trailer_url is not None:
            context['game'].trailer_url = context['game'].trailer_url[context['game'].trailer_url.rfind('/'):]
        revs = Review.objects.filter(game_id = context['game'].pk)
        context.update({
            'recommended': Game.objects.filter(is_active = True).exclude(pk = context['game'].pk).order_by('-hit_count_generic__hits')[:3],
            'reviews': revs,
            'review_count': revs.count(),
        })
        if revs.count() != 0:
            context.update({
                'average_rating':revs.aggregate(Sum('rating'))['rating__sum']/revs.count(),
            })
        else:
            context.update({
                'average_rating': 'No reviews'
            })

        for review in context['reviews']:
            review.likes = ReviewLike.objects.filter(review_id = review.pk, value = 1).count()
            review.dislikes = ReviewLike.objects.filter(review_id = review.pk, value = 0).count()

            try:
                review.is_liked = ReviewLike.objects.get(user_id = self.request.user.pk, review_id = review.pk, value = 1)
                review.is_liked = True
            except:
                review.is_liked = False
            try:
                review.is_disliked = ReviewLike.objects.get(user_id = self.request.user.pk,review_id = review.pk, value = 0)
                review.is_disliked = True
            except:
                review.is_disliked = False
        
        # print(context['reviews'][0].likes)
        return context
    
# def review_like(request, rid, uid):

# def review_

def create_review(request, gid,uid):
    game = Game.objects.get(pk=gid)
    if request.method != 'POST':
        form = ReviewForm()
    else:
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.author_id = uid
            review.game_id = gid
            review.save()
            return redirect('game_detail', pk=gid)
    return render(request, 'games/game_review.html', {'form':form, 'game':game})

def like_review(request,gid, rid, uid):
    try:
        like = ReviewLike.objects.get(user_id=uid, review_id = rid, value = 1).delete()
    except:
        like = ReviewLike.objects.create(user_id=uid, review_id = rid, value = 1)      
        try:
            like = ReviewLike.objects.get(user_id=uid, review_id = rid, value = 0).delete()
        except:
            pass
    return redirect('game_detail', pk=gid)

def dislike_review(request,gid, rid, uid):
    try:
        dislike = ReviewLike.objects.get(user_id=uid, review_id = rid, value = 0).delete()
    except:
        dislike = ReviewLike.objects.create(user_id=uid, review_id = rid, value = 0)      
        try:
            like = ReviewLike.objects.get(user_id=uid, review_id = rid, value = 1).delete()
        except:
            pass
    return redirect('game_detail', pk=gid)

def game_new(request):
    if request.method == "POST":    
        form = GameForm(request.POST, request.FILES)
        if form.is_valid():
            game = form.save(commit=False)
            game.save()
            return redirect('game_detail', pk=game.pk)
    else:
        form = GameForm()
    return render(request, 'games/game_new.html', {'form':form})

def game_edit(request, pk):
    game = Game.objects.get(pk=pk)
    if request.method == "POST":
        form = GameForm(request.POST, request.FILES, instance=game)
        if form.is_valid():
            game = form.save(commit=False)
            game.save()
            return redirect('game_detail', pk=game.pk)
    else:
        form = GameForm(instance=game)
    return render(request, 'games/game_new.html', {'form':form})

templates/games/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>  
    <div class="header">
        <p style="font-size: 50px; margin: 50px; color: white;">
            <a href="{% url 'games_list' %}">Games</a>
            <a href="{% url 'studios_list' %}">Studios</a>
            <a href="{% url 'publishers_list' %}">Publishers</a>
        </p>
        {% block new %}
        {% endblock %}
        <div style="float: right; color: white; margin-right: 20px;">
            {% if request.user.is_authenticated and request.user.is_active %}
                <p>User is logged in</p>
                <p>Username: {{ request.user.username }}</p>
                <a href="{% url 'change_password' %}"><button>Change password</button></a>   
                <a href="{% url 'logout' %}"><button>Log Out</button></a>
                {% if not perms.games.change_game %}
                <br> <a href="{% url 'get_mod' %}"><button>Become moderator</button></a>
                {% endif %}
            {% else %}
                <p>User is not logged in</p>
                <a href="{% url 'login' %}"><button>Log in</button></a>
                <a href="{% url 'register' %}"><button>Register</button></a>
            {% endif %}
        </div>
    </div>
    <div class="filter">
        {% block filter %}
        {% endblock %}
    </div>
    <div class="content">
            {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/games/game_detail.html
{% extends 'games/base.html' %}
{% load hitcount_tags %}

{% block content %}
    <div class="game_card">  
        <div class="game_card">  
            <div class="game_card_top">
                <a href="{% url 'game_detail' pk=game.pk%}"><p class="game_title">{{game.title}}</p></a>
            </div>
            {% if perms.games.change_game %}
            <div class="game_edit">
                <a href="{% url 'game_edit' pk=game.pk %}">
                    {% include 'icons/three-dots-vertical.svg' %}
                </a>
            </div>
            {% endif %}
        <img src="/media/{{game.poster}}" alt="">
        <p>Company: {{game.studio}}</p>
        <p>{{game.release_date}}</p>
        <p>{{game.genre}}</p>
        <p>{{game.style}}</p>
        <p>{{game.desc}}</p>
        <p>{{game.publisher}}</p>
        <p>{{game.rating_metacritic}}</p>
        <p>{{game.rating_ign}}</p>
        <p>{{game.price }}</p>
        <p>Views: {% get_hit_count for game %}</p>
    </div>
    {% if game.trailer_url is not None %}
    <div style="margin: auto;">
        <iframe width="560" height="315" 
            src="https://www.youtube.com/embed/{{game.trailer_url}}" 
            title="YouTube video player" 
            N9wt_cnSCdE
            frameborder="0" 
            allow="
                accelerometer; 
                autoplay; 
                clipboard-write; 
                encrypted-media; 
                gyroscope; 
                picture-in-picture; 
                web-share" 
            allowfullscreen>
        </iframe>
    </div>

    {% endif %}
    <div class="recommended">
        {% for rec in recommended %}
            <a href="{% url 'game_detail' pk=rec.pk %}">{{rec.title}}</a>
        {% endfor %}
    </div>

    <div>
        <div>
            <p>Avg: {{average_rating}} | Amt: {{review_count}}</p></p>
        </div>
        {% if user.is_authenticated %}
        <p><a href="{% url 'create_review' uid=user.pk gid=game.pk %}"><button>Review</button></a></p>
        {% endif %}
        {% for review in reviews %}
            <div style="background-color: white;">
                <p>{{ review.author }}</p>
                <p>{{ review.comment }}</p>
                <p>{{ review.rating }}</p>
                <p>{{ review.rating_date }}</p>
                <div class="likes">
                    <p>
                        {% if user.is_authenticated %}
                            {% if not review.is_liked %}
                            <a href="{% url 'like_review' gid=game.pk rid=review.pk uid=user.pk %}">
                                <span class="button">{% include 'icons/arrow-up.svg' %} {{ review.likes }}</span>
                            </a>
                            {% else %}
                            <a href="{% url 'like_review' gid=game.pk rid=review.pk uid=user.pk %}">
                                <span class="button-like">{% include 'icons/arrow-up.svg' %} {{ review.likes }}</span>
                            </a>
                            {% endif %}
                        {% else %}
                        <span class="button">{% include 'icons/arrow-up.svg' %} {{ review.likes }}</span>
                        {% endif %}
                        |
                        {% if user.is_authenticated %}
                        <a href="{% url 'dislike_review' gid=game.pk rid=review.pk uid=user.pk %}">
                            {% if not review.is_disliked %}
                                <span class="button">{% include 'icons/arrow-down.svg' %} {{ review.dislikes }}</span></a>

                            {% else %}
                                <span class="button-dislike">{% include 'icons/arrow-down.svg' %} {{ review.dislikes }}</span></a>
                            {% endif %}
                        {% else %}
                        <span class="button-like">{% include 'icons/arrow-down.svg' %} {{ review.dislikes }}</span>
                        {% endif %}
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/games/game_new.html
{% extends 'games/base.html' %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

templates/games/game_review.html
{% extends 'games/base.html' %}

{% block content %}
<div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Post</button>
    </form>
</div>
{% endblock %}

templates/games/games_list.html
{% extends 'games/base.html' %}

{% block new %}
    {% if perms.games.change_game %}
        <a href="{% url 'game_new' %}" style="float: left; font-size: 50px; margin-top: 50px; margin-left: 50px;">
            {% include '../icons/file-earmark-plus.svg' %}
    </a>
    {% endif %}
{% endblock%}

{% block filter %}
    <div class="filter">
        <form method="GET">
            {{filter.form.as_p}}
            <button type="submit">Search</button>
        </form>
    </div>
{% endblock %}

{% block content %}
    {% for game in page_obj %}
        {% if game.is_active %}
        <div class="game_card">  
            <div class="game_card_top">
                <a href="{% url 'game_detail' pk=game.pk%}"><p class="game_title">{{game.title}}</p></a>
            </div>
            {% if perms.games.change_game %}
            <div class="game_edit">
                <a href="{% url 'game_edit' pk=game.pk %}">
                    {% include 'icons/three-dots-vertical.svg' %}
                </a>
            </div>
            {% endif %}
            <p>{{game.studio}}</p>
            <p>{{game.desc}}</p>
        </div>
        {% endif %}
    {% endfor %}
    <div class="paginator" style="margin: auto;">
        <span>
            {% if page_obj.has_previous %}
                <a href="?page=1">first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span>
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last</a>
            {% endif %}
        </span>
    </div>
{% endblock %}