games/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AllGamesView.as_view(), name='games_list'),
    path('<int:pk>',views.GameView.as_view(), name='game_detail'),
    path('new', views.game_new, name='game_new'),
    path('edit/<int:pk>', views.game_edit, name='game_edit'),
    path('review/<int:gid>/<int:uid>',views.create_review, name='create_review'),
    path('reviewlike/<int:gid>/<int:rid>/<int:uid>/', views.like_review, name='like_review'),
    path('reviewdislike/<int:gid>/<int:rid>/<int:uid>/', views.dislike_review, name='dislike_review'),
]

projectsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('games.urls')),
    path('studios/',include('studios.urls')),
    path('publishers/', include('publishers.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('users/',include('users.urls')),
    path('captcha/', include('captcha.urls')),
    path(r'^tracking', include('tracking.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

studios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AllStudiosView.as_view(), name='studios_list'),
    path('<int:pk>/', views.StudioView.as_view(), name='studio_detail'),
    path('new', views.studio_new, name='studio_new'),
    path('edit/<int:pk>', views.studio_edit, name='studio_edit'),
]

studios/models.py
from django.db import models

from hitcount.models import HitCount
from hitcount.models import HitCountMixin

from django.contrib.contenttypes.fields import GenericRelation

class Studio(models.Model, HitCountMixin):
    name = models.CharField(max_length=100,verbose_name='Издатель')
    logo = models.ImageField(upload_to="studio_logos",null=True,verbose_name='Логотип')
    headquarters = models.CharField(max_length=100,verbose_name='Адрес')
    founder = models.CharField(max_length=200,verbose_name='Основатель')
    founded = models.DateField(verbose_name='Основано')
    games = models.TextField(verbose_name='Список игр')
    main_site = models.URLField(max_length=200,verbose_name='Главная Страница')
    is_active = models.BooleanField(default=True,verbose_name='Активен')
    
    hit_count_generic = GenericRelation(
        HitCount, 
        object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')

    def current_hitcount(self):
        return self.hit_count.hits
    
    def current_hitcount_in_last(self, num):
        return self.hit_count.hits_in_last(days=num)

    def __str__(self) -> str:
        return self.name

studios/forms.py
from django import forms
from .models import Studio

class StudioForm(forms.ModelForm):
    class Meta:
        model = Studio
        fields = '__all__'
        exclude = ('is_active',)

studios/views.py
from typing import Any, Dict
from django.shortcuts import render,redirect
from .models import Studio
from games.models import Game
from .forms import StudioForm
from django.views.generic import ListView,DetailView

from hitcount.views import HitCountDetailView

class AllStudiosView(ListView):
    model = Studio
    paginate_by = 5
    # queryset = Game.objects.filter()
    template_name = 'studios/studios_list.html'
    context_object_name = 'studios'

class StudioView(HitCountDetailView):
    model = Studio
    template_name = 'studios/studio_detail.html'
    context_object_name = 'studio'
    count_hit = True

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        games_list = Game.objects.filter(studio = context['studio'].pk, is_active = True)
        context['games_list'] = games_list
        context.update({
            'recommended': Studio.objects.filter(is_active = True).exclude(pk = context['studio'].pk).order_by('-hit_count_generic__hits')[:3]
        })
        return context
    
def studio_new(request):
    if request.method == "POST":    
        form = StudioForm(request.POST, request.FILES)
        if form.is_valid():
            studio = form.save(commit=False)
            studio.save()
            return redirect('studio_detail', pk=studio.pk)
    else:
        form = StudioForm()
    return render(request, 'studios/studio_new.html', {'form':form})

def studio_edit(request, pk):
    studio = Studio.objects.get(pk=pk)
    if request.method == "POST":
        form = StudioForm(request.POST, request.FILES, instance=studio)
        if form.is_valid():
            studio = form.save(commit=False)
            studio.save()
            return redirect('studio_detail', pk=studio.pk)
    else:
        form = StudioForm(instance=studio)
    return render(request, 'studios/studio_new.html', {'form':form})

templates/studios/studio_detail.html
{% extends 'games/base.html' %}
{% load hitcount_tags %}

{% block content %}
<div class="game_card" style="border-bottom: 2px black solid; margin: 10px;">    
    <div class="game_card_top">
        <div class="game_title">
            <p class>{{studio.name}}</p>
        </div>
        {% if perms.studios.change_studio %}
        <div class="game_edit">
            <a href="{% url 'studio_edit' pk=studio.pk %}">
                {% include 'icons/three-dots-vertical.svg' %}
            </a>
        </div>
        {% endif %}
    </div>
    <img src="/media/{{studio.logo}}" alt="">
    <p>{{studio.headquarters}}</p>
    <p>{{studio.main_site}}</p>
    <p>{{studio.founder}}</p>
    <p>{{studio.founded}}</p>
    <p>Views: {% get_hit_count for studio %}</p>
    {% for game in games_list %}
        <p>{{ game.title }}</p> 
    {% endfor %} 
</div>
<div class="recommended">
    {% for rec in recommended %}
        <a href="{% url 'studio_detail' pk=rec.pk %}">{{rec.name}}</a>
    {% endfor %}
</div>
{% endblock %}

templates/studios/studio_new.html
{% extends 'games/base.html' %}

{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
{% endblock %}

templates/studios/studios_list.html
{% extends 'games/base.html' %}
{% block new %}
<a href="{% url 'studio_new' %}" style="float: left; font-size: 50px; margin-top: 50px; margin-left: 50px;">
    {% include '../icons/file-earmark-plus.svg' %}
</a>
{% endblock%}
{% block content %}
    {% for studio in studios %}
        <div class="game_card" style="border-bottom: 2px black solid; margin: 10px;">    
            <a href="{% url 'studio_detail' pk=studio.pk %}"><p>{{studio.name}}</p></a>
            <p>{{studio.headquarters}}</p>
            <p>{{studio.main_site}}</p>
            {% for game in studio.games_list %}
                <p>{{game.title}} </p>
            {% endfor %}    
        </div>
    {% endfor %}
{% endblock %}